// File __EUNIT_TestControl_CoreTimerBF609_Core0.cpp generated by E-UNIT program
// Author: kpore
// Date: Sat 2019/11/23 at 02:43:08 PM

#define HUMAN_INTERVENTION_TEST_LEVEL 20
#define ALL_TEST_LEVELS 0xFFFF

void AutomatedTestLevelControl(void)
{
    return;
}